### PR TITLE
Support returndata view

### PR DESCRIPTION
**Pull request by andy3520**
As I mention in #74 I couldn't found a way to view the returnValue so I create this PR

Added: 
- AccodionJsonView wrapped SimpleJsonView
- Added view for job returnData
Update:
- Use AccodionJsonView for job data and stracktrace

Screenshots:
image
image

### CODE REVIEW

**Comment by s-r-x** [comment]
@andy3520 hi, actually there is a way to get the return value by clicking on the "i" icon (which isn't very convenient though).
This accordions thing looks good, but there's definitely should be some preferences for specifying which of these little guys are opened by default. Can you add it?

**Comment by andy3520** [comment]
@s-r-x done. I updated it, pls take a look.

**Comment by s-r-x** [comment]
@andy3520 sorry man, i messed up something with github, but your work has been merged. ty

**Comment by andy3520** [comment]
nw, if its merged anyway I'm okay, just need that feature :D

**Pull request closed without merging**
