### PR TITLE
fix pagination readability issue

### PR DESCRIPTION
**Pull request by weilinzung**
Before:

If the table with a lot of jobs, the bottom sticky pagination would have the readability issue.

Screen Shot 2021-05-11 at 3 51 29 PM

After:

Just simply add the background color for it.

Screen Shot 2021-05-11 at 3 51 10 PM
Screen Shot 2021-05-11 at 3 48 55 PM

### CODE REVIEW

**Comment by weilinzung** [comment]
@s-r-x please take a look. thanks!

**Comment by s-r-x** [comment]
n1

**Comment by weilinzung** [comment]
@s-r-x thank you. Can you also release it?

**Comment by weilinzung** [comment]
@s-r-x can you also update this to the latest version?  I believe the 0.8.0 is the fix!
https://github.com/s-r-x/bull-monitor/blob/main/packages/express/package.json#L24

**Pull request merged**
